// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IsAgent, IsAgentTableId } from "./tables/IsAgent.sol";
import { IsNPC, IsNPCTableId } from "./tables/IsNPC.sol";
import { MovementCost, MovementCostTableId } from "./tables/MovementCost.sol";
import { Altitude, AltitudeTableId } from "./tables/Altitude.sol";
import { IsObstruction, IsObstructionTableId } from "./tables/IsObstruction.sol";
import { MaxHP, MaxHPTableId } from "./tables/MaxHP.sol";
import { MoveSpeed, MoveSpeedTableId } from "./tables/MoveSpeed.sol";
import { Strength, StrengthTableId } from "./tables/Strength.sol";
import { Recovery, RecoveryTableId } from "./tables/Recovery.sol";
import { Weight, WeightTableId } from "./tables/Weight.sol";
import { ActionRecovery, ActionRecoveryTableId } from "./tables/ActionRecovery.sol";
import { CurrentHP, CurrentHPTableId } from "./tables/CurrentHP.sol";
import { Stone, StoneTableId } from "./tables/Stone.sol";
import { Wood, WoodTableId } from "./tables/Wood.sol";
import { Cord, CordTableId } from "./tables/Cord.sol";
import { Berry, BerryTableId } from "./tables/Berry.sol";
import { Fish, FishTableId } from "./tables/Fish.sol";
import { IsPushable, IsPushableTableId } from "./tables/IsPushable.sol";
import { IsMinable, IsMinableTableId } from "./tables/IsMinable.sol";
import { IsChopable, IsChopableTableId } from "./tables/IsChopable.sol";
import { IsFishable, IsFishableTableId } from "./tables/IsFishable.sol";
import { IsLootable, IsLootableTableId } from "./tables/IsLootable.sol";
import { IsItem, IsItemTableId } from "./tables/IsItem.sol";
import { IsEquipment, IsEquipmentTableId } from "./tables/IsEquipment.sol";
import { CanAttack, CanAttackTableId } from "./tables/CanAttack.sol";
import { CanShoot, CanShootTableId } from "./tables/CanShoot.sol";
import { CanThrow, CanThrowTableId } from "./tables/CanThrow.sol";
import { CanChop, CanChopTableId } from "./tables/CanChop.sol";
import { CanMine, CanMineTableId } from "./tables/CanMine.sol";
import { CanFish, CanFishTableId } from "./tables/CanFish.sol";
import { EquipedItem, EquipedItemTableId } from "./tables/EquipedItem.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { ClientContext, ClientContextTableId } from "./tables/ClientContext.sol";
import { IsBearSpawner, IsBearSpawnerTableId } from "./tables/IsBearSpawner.sol";
import { IsWolfSpawner, IsWolfSpawnerTableId } from "./tables/IsWolfSpawner.sol";
